import base64
import os

import cv2
import numpy as np
from PIL import ExifTags, Image

from face_utils import (CROP_SIZE, blendshapes, create_landmarker, crop_face,
                        face_bbox, to_mp_image)

IMAGE_EXT = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
VIDEO_EXT = {".mp4", ".avi", ".mov", ".mkv", ".webm"}
MAX_SAMPLED_FRAMES = 30
GENERATIVE_OR_EDITING_SOFTWARE = (
    "midjourney", "dall-e", "dalle", "stable diffusion", "stability ai",
    "runway", "firefly", "photoshop", "gimp", "canva", "snapseed",
)


def artifact_score(face_bgr) -> float:
    gray = cv2.cvtColor(face_bgr, cv2.COLOR_BGR2GRAY).astype(np.float32)
    noise = cv2.Laplacian(gray, cv2.CV_32F).var()

    mag = np.abs(np.fft.fftshift(np.fft.fft2(gray)))
    h, w = gray.shape
    yy, xx = np.ogrid[:h, :w]
    radius = np.sqrt((yy - h / 2) ** 2 + (xx - w / 2) ** 2)
    high_freq_ratio = mag[radius > min(h, w) * 0.35].sum() / (mag.sum() + 1e-8)

    noise_term = np.clip(noise / 150.0, 0, 1)
    freq_term = np.clip(1 - abs(high_freq_ratio - 0.12) / 0.12, 0, 1)
    return float((noise_term + freq_term) / 2)


def ela_signal(frame_bgr, bbox) -> tuple:
    ok, enc = cv2.imencode(".jpg", frame_bgr, [cv2.IMWRITE_JPEG_QUALITY, 90])
    if not ok:
        return 0.5, "ELA skipped (could not re-encode the image)."
    recompressed = cv2.imdecode(enc, cv2.IMREAD_COLOR)
    error = cv2.absdiff(frame_bgr, recompressed).astype(np.float32).mean(axis=2)

    h, w = error.shape
    x1, y1, x2, y2 = bbox
    face_error = error[y1:y2, x1:x2].mean() if y2 > y1 and x2 > x1 else None
    mask = np.ones((h, w), dtype=bool)
    mask[y1:y2, x1:x2] = False
    bg_error = error[mask].mean() if mask.any() else None

    if face_error is None or bg_error is None or bg_error < 1e-6:
        return 0.5, "ELA skipped (face box covers the whole frame)."

    ratio = face_error / bg_error
    deviation = abs(np.log(ratio + 1e-6))
    score = float(np.clip(1 - deviation / 1.5, 0, 1))
    return score, (f"Error-level analysis: face-region recompression error is "
                    f"{ratio:.2f}x the background's (1.0x = consistent compression history).")


def exif_signal(path) -> tuple:
    try:
        img = Image.open(path)
        raw = img._getexif() if hasattr(img, "_getexif") else None
    except Exception:
        return 0.5, "EXIF metadata could not be read."

    if not raw:
        return 0.5, ("No EXIF metadata found (common for screenshots, messaging apps, and some "
                      "AI-generated images -- not conclusive either way).")

    tags = {ExifTags.TAGS.get(k, k): v for k, v in raw.items()}
    software = str(tags.get("Software", "")).lower()
    for kw in GENERATIVE_OR_EDITING_SOFTWARE:
        if kw in software:
            return 0.15, f"EXIF 'Software' tag mentions '{tags.get('Software')}' (edited/generated by a tool)."

    if tags.get("Make") or tags.get("Model"):
        cam = " ".join(str(tags.get(k, "")) for k in ("Make", "Model") if tags.get(k)).strip()
        return 0.8, f"EXIF shows camera metadata ({cam}) -- consistent with an unedited camera photo."

    return 0.5, "EXIF metadata present but has no camera make/model recorded."


def _encode_thumbnail(frame_bgr, bbox) -> str:
    annotated = frame_bgr.copy()
    x1, y1, x2, y2 = bbox
    cv2.rectangle(annotated, (x1, y1), (x2, y2), (0, 200, 0), 2)
    ok, buf = cv2.imencode(".jpg", annotated)
    return base64.b64encode(buf).decode("ascii") if ok else ""


def _reset(classifiers):
    for clf in classifiers:
        clf.scores = []


def _score_crop(crop, classifiers) -> dict:
    return {clf.name: clf.score(crop) for clf in classifiers}


def _verdict(components: dict) -> dict:
    """components: name -> (score 0..1, weight). Weights don't need to sum to 1."""
    if not components:
        return {"overall_score": None, "verdict": "Uncertain"}
    total_weight = sum(w for _, w in components.values()) or 1.0
    overall = sum(s * w for s, w in components.values()) / total_weight
    if overall >= 0.62:
        label = "Likely real"
    elif overall >= 0.4:
        label = "Uncertain"
    else:
        label = "Likely manipulated"
    return {"overall_score": round(float(overall), 3), "verdict": label}


def analyze_image(path, classifiers) -> dict:
    _reset(classifiers)
    frame = cv2.imread(path)
    if frame is None:
        raise ValueError("Could not read image file")

    landmarker = create_landmarker(video=False, max_faces=1)
    try:
        result = landmarker.detect(to_mp_image(frame))
    finally:
        landmarker.close()

    if not result.face_landmarks:
        return {
            "media_type": "image", "faces_detected": False, "verdict": "No face found",
            "overall_score": None, "reasons": ["No face detected in the image."],
        }

    lm = result.face_landmarks[0]
    bbox = face_bbox(lm, frame.shape[1], frame.shape[0])
    crop = crop_face(frame, lm, CROP_SIZE)

    reasons = []
    components = {}
    model_scores = {}
    if crop is None:
        reasons.append("Could not extract a usable face crop (face too close to the frame edge).")
    else:
        if classifiers:
            model_scores = _score_crop(crop, classifiers)
            components["model"] = (float(np.mean(list(model_scores.values()))), 0.5)
            for name, s in model_scores.items():
                reasons.append(f"{name} model: P(genuine) = {s:.2f}")
        a_score = artifact_score(crop)
        components["artifact"] = (a_score, 0.2)
        reasons.append(f"Artifact-naturalness score {a_score:.2f}/1 "
                        "(noise + frequency profile vs. a typical camera photo).")

    ela_score, ela_reason = ela_signal(frame, bbox)
    components["ela"] = (ela_score, 0.2)
    reasons.append(ela_reason)

    exif_score, exif_reason = exif_signal(path)
    components["exif"] = (exif_score, 0.1)
    reasons.append(exif_reason)

    if not classifiers:
        reasons.append("No trained model supplied -- verdict is heuristic-only, low confidence. "
                        "Train one with classifier.py for a reliable result.")

    out = {"media_type": "image", "faces_detected": True, "reasons": reasons,
           "thumbnail": _encode_thumbnail(frame, bbox)}
    out.update(_verdict(components))
    return out


def analyze_video(path, classifiers) -> dict:
    _reset(classifiers)
    cap = cv2.VideoCapture(path)
    if not cap.isOpened():
        raise ValueError("Could not open video file")

    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) or 0
    fps = cap.get(cv2.CAP_PROP_FPS) or 25.0
    every = max(1, total // MAX_SAMPLED_FRAMES) if total else 5

    landmarker = create_landmarker(video=True, max_faces=1)
    artifact_scores, blink_closed, blink_count = [], False, 0
    sampled = with_face = 0
    thumb_frame = thumb_bbox = None
    ts_ms = 0
    prev_small = None
    duplicate_frames = compared_frames = 0
    try:
        i = 0
        while True:
            ok, frame = cap.read()
            if not ok:
                break

            small = cv2.resize(frame, (32, 32), interpolation=cv2.INTER_AREA).astype(np.float32)
            if prev_small is not None:
                compared_frames += 1
                if np.abs(small - prev_small).mean() < 0.5:
                    duplicate_frames += 1
            prev_small = small

            if i % every == 0:
                sampled += 1
                result = landmarker.detect_for_video(to_mp_image(frame), ts_ms)
                ts_ms += 33
                if result.face_landmarks:
                    with_face += 1
                    lm = result.face_landmarks[0]
                    bbox = face_bbox(lm, frame.shape[1], frame.shape[0])
                    if thumb_frame is None:
                        thumb_frame, thumb_bbox = frame, bbox
                    crop = crop_face(frame, lm, CROP_SIZE)
                    if crop is not None:
                        if classifiers:
                            _score_crop(crop, classifiers)
                        artifact_scores.append(artifact_score(crop))
                    if result.face_blendshapes:
                        bs = blendshapes(result)
                        score = (bs.get("eyeBlinkLeft", 0) + bs.get("eyeBlinkRight", 0)) / 2
                        if not blink_closed and score > 0.5:
                            blink_closed = True
                        elif blink_closed and score < 0.25:
                            blink_closed = False
                            blink_count += 1
            i += 1
    finally:
        cap.release()
        landmarker.close()

    if with_face == 0:
        return {
            "media_type": "video", "faces_detected": False, "verdict": "No face found",
            "overall_score": None, "reasons": [f"No face detected in any of {sampled} sampled frames."],
        }

    reasons = [f"Face detected in {with_face}/{sampled} sampled frames."]
    components = {}
    if classifiers:
        for clf in classifiers:
            reasons.append(f"{clf.name} model: mean P(genuine) = {clf.mean_score():.2f} "
                            f"over {len(clf.scores)} frames")
        components["model"] = (float(np.mean([c.mean_score() for c in classifiers])), 0.5)

    if artifact_scores:
        a = float(np.mean(artifact_scores))
        components["artifact"] = (a, 0.2)
        reasons.append(f"Mean artifact-naturalness score {a:.2f}/1 across sampled frames.")

    duration = total / fps if total else sampled * every / fps
    if duration >= 2.0:
        if blink_count == 0:
            reasons.append(f"No blink detected across a ~{duration:.1f}s clip -- unusual for a live "
                            "person on camera and can indicate a static or looping source.")
            components["liveness"] = (0.25, 0.2)
        else:
            reasons.append(f"{blink_count} natural blink(s) detected -- consistent with a live subject.")
            components["liveness"] = (0.9, 0.2)

    if compared_frames:
        dup_ratio = duplicate_frames / compared_frames
        reasons.append(f"{duplicate_frames}/{compared_frames} consecutive frame-pairs are near-identical "
                        f"({dup_ratio:.0%}).")
        if dup_ratio > 0.1:
            reasons.append("A high near-duplicate-frame ratio can indicate a looped, paused, or "
                            "frame-repeated clip rather than a continuous live capture.")
        dup_score = float(np.clip(1 - dup_ratio / 0.3, 0, 1))
        components["frame_continuity"] = (dup_score, 0.1)

    if not classifiers:
        reasons.append("No trained model supplied -- verdict is heuristic-only, low confidence. "
                        "Train one with classifier.py for a reliable result.")

    out = {"media_type": "video", "faces_detected": True, "reasons": reasons}
    out.update(_verdict(components))
    if thumb_frame is not None:
        out["thumbnail"] = _encode_thumbnail(thumb_frame, thumb_bbox)
    return out

FACE_SHAPE_LANDMARKS = [33, 263, 1, 61, 291, 152, 10, 234, 454]

def _landmark_vector(landmarks) -> np.ndarray:
    pts = np.array([[landmarks[i].x, landmarks[i].y] for i in FACE_SHAPE_LANDMARKS])
    eye_dist = np.linalg.norm(pts[0] - pts[1]) + 1e-8
    pts = pts / eye_dist
    diffs = [np.linalg.norm(pts[a] - pts[b])
             for a in range(len(pts)) for b in range(a + 1, len(pts))]
    return np.array(diffs, dtype=np.float32)


def _first_face(path):
    ext = os.path.splitext(path)[1].lower()
    if ext in IMAGE_EXT:
        frame = cv2.imread(path)
        if frame is None:
            raise ValueError("Could not read image file")
        landmarker = create_landmarker(video=False, max_faces=1)
        try:
            result = landmarker.detect(to_mp_image(frame))
        finally:
            landmarker.close()
        if not result.face_landmarks:
            return None, None, None, 1
        lm = result.face_landmarks[0]
        return frame, lm, face_bbox(lm, frame.shape[1], frame.shape[0]), 1

    if ext in VIDEO_EXT:
        cap = cv2.VideoCapture(path)
        if not cap.isOpened():
            raise ValueError("Could not open video file")
        landmarker = create_landmarker(video=True, max_faces=1)
        checked, ts_ms = 0, 0
        try:
            for _ in range(60):
                ok, frame = cap.read()
                if not ok:
                    break
                checked += 1
                result = landmarker.detect_for_video(to_mp_image(frame), ts_ms)
                ts_ms += 33
                if result.face_landmarks:
                    lm = result.face_landmarks[0]
                    return frame, lm, face_bbox(lm, frame.shape[1], frame.shape[0]), checked
        finally:
            cap.release()
            landmarker.close()
        return None, None, None, checked

    raise ValueError(f"Unsupported file extension: {ext}")


def compare_faces(path_a, path_b) -> dict:
    frame_a, lm_a, bbox_a, checked_a = _first_face(path_a)
    frame_b, lm_b, bbox_b, checked_b = _first_face(path_b)

    if lm_a is None or lm_b is None:
        missing, checked = ("first", checked_a) if lm_a is None else ("second", checked_b)
        return {"faces_detected": False,
                "reason": f"No face detected in the {missing} file (checked {checked} frame(s))."}

    vec_a, vec_b = _landmark_vector(lm_a), _landmark_vector(lm_b)
    cos_sim = float(np.dot(vec_a, vec_b) / (np.linalg.norm(vec_a) * np.linalg.norm(vec_b) + 1e-8))
    similarity = float(np.clip((cos_sim - 0.90) / 0.10, 0, 1))

    if similarity >= 0.65:
        verdict = "Likely the same person"
    elif similarity >= 0.35:
        verdict = "Uncertain"
    else:
        verdict = "Likely different people"

    return {
        "faces_detected": True,
        "similarity": round(similarity, 3),
        "verdict": verdict,
        "reason": ("Geometric landmark comparison only (no deep face-recognition model). Most "
                   "human faces share similar proportions, so this method is much better at "
                   "catching a clear mismatch than at confirming a match -- treat a low score "
                   "as meaningful, a high score as inconclusive, not as a verified identity match."),
        "thumbnail_a": _encode_thumbnail(frame_a, bbox_a),
        "thumbnail_b": _encode_thumbnail(frame_b, bbox_b),
    }


def analyze_file(path, classifiers) -> dict:
    ext = os.path.splitext(path)[1].lower()
    if ext in IMAGE_EXT:
        return analyze_image(path, classifiers)
    if ext in VIDEO_EXT:
        return analyze_video(path, classifiers)
    raise ValueError(f"Unsupported file extension: {ext}")


def main():
    import argparse
    import json

    from liveness import OnnxFaceClassifier

    p = argparse.ArgumentParser(description="Analyze a photo or video for real/fake signals")
    p.add_argument("--input", required=True)
    p.add_argument("--spoof-model", help="ONNX live/spoof model from classifier.py")
    p.add_argument("--deepfake-model", help="ONNX real/fake model from classifier.py")
    args = p.parse_args()

    classifiers = []
    if args.spoof_model:
        classifiers.append(OnnxFaceClassifier(args.spoof_model, "anti-spoof"))
    if args.deepfake_model:
        classifiers.append(OnnxFaceClassifier(args.deepfake_model, "deepfake"))

    result = analyze_file(args.input, classifiers)
    result.pop("thumbnail", None)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
